### ISSUE TITLE
Import lexicon and inflections/forms

### ISSUE THREAD

**Issue by craigp-atw** [presciencelabs/tabitha-targets#4]
A main part of a target database is the lexicon. The lexicon includes the target word, gloss, features, and forms/inflections. All of this data should be imported and it can be made available to the user.

**Comment by longrunningprocess** [comment]
# pairing session

## refactor current `English` table

move into `Text` table with `language` column of `English`

## Add `Lexicon` table 

### Taken from the following "part-of-speech" tables:

`Adjectives`, `Adpositions`, `Adverbs`, `Nouns`, `Verbs`

> ❓ `Conjunctions`

![image](https://github.com/presciencelabs/tabitha-targets/assets/4412848/b6f0fd8a-bd60-49a5-81b3-f00ba3a76362)

> ❓ `Particles`

![image](https://github.com/presciencelabs/tabitha-targets/assets/4412848/d92f5010-b4c8-43f6-931c-dc923bd6ac45)

> ❓ `Pronouns`

![image](https://github.com/presciencelabs/tabitha-targets/assets/4412848/bcf5bbe6-ba12-44ed-ab8b-eaa1fd432b7a)

### Data

- `stem` from `Roots`
- `part-of-speech` from table name
- `gloss` from `Glosses`
- `features` from `Features`
- `forms` loaded from separate process, e.g., `|celebrated|celebrated|celebrating|celebrates|`

**Comment by longrunningprocess** [comment]
# ⚠️ MIGRATION STRATEGY ⚠️ 

Do not merge PR into `main` until consumers have migrated... they should utilize `[refactor-db-include-inflecti.targets-ayz.pages.dev](https://refactor-db-include-inflecti.targets-ayz.pages.dev/)` for requests to this new API.

**Comment by longrunningprocess** [comment]
After discussing #5 a little further, it was determined we need to also include the `Constituents` column from each of the part_of_speech tables.
